language: android
jdk: oraclejdk8
android: 
  components: 
    - tools 
    - platform-tools 
    - android-29.0.2
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
before_script:
  - cd androidApp
script:
  - ./gradlew build
