package io.github.nadzwyczajnaGrupaRobocza.texaspoker.game.cards

val clubsFive = Card(Suit.Clubs, Rank.Five)
val clubsFour = Card(Suit.Clubs, Rank.Four)
val diamondsAce = Card(Suit.Diamonds, Rank.Ace)
val diamondsKing = Card(Suit.Diamonds, Rank.King)
val diamondsFive = Card(Suit.Diamonds, Rank.Five)
val diamondsSix = Card(Suit.Diamonds, Rank.Six)
val diamondsSeven = Card(Suit.Diamonds, Rank.Seven)
val diamondsEight = Card(Suit.Diamonds, Rank.Eight)
val diamondsTen = Card(Suit.Diamonds, Rank.Ten)
val diamondsJack = Card(Suit.Diamonds, Rank.Jack)
val heartsFive = Card(Suit.Hearts, Rank.Five)
val heartsFour = Card(Suit.Hearts, Rank.Four)
val heartsNine = Card(Suit.Hearts, Rank.Nine)
val heartsThree = Card(Suit.Hearts, Rank.Three)
val spadesFive = Card(Suit.Spades, Rank.Five)
val spadesQueen = Card(Suit.Spades, Rank.Queen)
val spadesThree = Card(Suit.Spades, Rank.Three)
val spadesTwo = Card(Suit.Spades, Rank.Two)
