package io.github.nadzwyczajnaGrupaRobocza.texaspoker.game.cards

val diamondsKing = Card(Suit.Diamonds, Rank.King)
val spadesQueen = Card(Suit.Spades, Rank.Queen)
val diamondsTen = Card(Suit.Diamonds, Rank.Ten)
val hearsNine = Card(Suit.Hearts, Rank.Nine)
val spadesThree = Card(Suit.Spades, Rank.Three)
val hearsThree = Card(Suit.Hearts, Rank.Three)
val clubsFour = Card(Suit.Clubs, Rank.Four)
val clubsFive = Card(Suit.Clubs, Rank.Five)
val spadesFive = Card(Suit.Spades, Rank.Five)
val hearsFive = Card(Suit.Hearts, Rank.Five)
val hearsFour = Card(Suit.Hearts, Rank.Four)
val diamondsSix = Card(Suit.Diamonds, Rank.Six)
val spadesTwo = Card(Suit.Spades, Rank.Two)
